name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17.2.0

      - name: Install dependencies for application under test
        run: npm i

      - name: run application under test
        run: npm run dev

      - name: Install dependencies for automated tests
        run: npm i
        working-directory: ./automated_tests

      - name: Install Playwright Browsers
        run: npx playwright install
        working-directory: ./automated_tests

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./automated_tests

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30